### ISSUE TITLE
Repo not find

### ISSUE THREAD

**Issue by HosseinSheikhi** [RIF-Robotics/dingo_setup#1]
Hi, 
At the very first step, `git clone git@github.com:cosmosrobotics/dingo_setup.git ` returns `ERROR: Repository not found.`
I could not find the `cosmos robotics` github.

**Comment by SyllogismRXS** [comment]
I fixed some URLs in the README. Give it another try.

**Comment by sgarciav** [comment]
Closing this issue as it has been addressed.
